<?php

return [
    'name' => 'Rashid Ahamed P',
    'short_name' => 'Rashid Ahamed',
    'initials' => 'RA',
    'title' => 'Cloud & DevOps Engineer',
    'roles' => [
        'Cloud & DevOps Engineer',
        'Kubernetes Engineer',
        'Platform Engineer',
        'Cloud Architect',
    ],
    'status_line' => 'Senior Cloud & DevOps Engineer · Kerala, IN · 7+ yrs in IT',
    'tagline' => 'Senior Cloud & DevOps Engineer based in Kerala, India — AWS, Azure, GCP, Kubernetes, and CI/CD.',
    'location' => 'Kerala, India',
    'timezone' => 'IST',
    'email' => 'rashidpokkat@gmail.com',
    'phone' => '+91 9544829782',
    'phone_raw' => '919544829782',
    'social' => [
        'linkedin' => 'https://www.linkedin.com/in/rashidpokkat/',
        'instagram' => 'https://www.instagram.com/rashidahamed_/',
        'facebook' => 'https://www.facebook.com/rashidpokkat',
        'whatsapp' => 'https://wa.me/919544829782',
        'github' => 'https://github.com/rashidpokkat',
        'email' => 'mailto:rashidpokkat@gmail.com',
    ],
    'stats' => [
        ['value' => '7+', 'label' => 'Years experience'],
        ['value' => '3+', 'label' => 'Years in DevOps'],
        ['value' => '3', 'label' => 'Cloud platforms'],
        ['value' => '3', 'label' => 'Certifications'],
    ],
    'about' => 'Senior Cloud and DevOps Engineer based in Kerala, India, with 7+ years in IT and 3+ years focused on cloud platforms and automation. At Jio Platforms Limited I design CI/CD pipelines with Jenkins, GitLab, and ArgoCD, and automate Kubernetes deployments across AKS, EKS, and GKE with Helm and Terraform. Previously at Karkinos Healthcare I delivered multi-cloud solutions on AWS, Azure, and GCP — cutting deployment time by 40% — and set up production monitoring with Prometheus and Grafana. Earlier roles in the UAE and Kerala grounded me in Linux, networking, and reliable operations. RHCSA certified. Open to Cloud, DevOps, and platform engineering work where reliability and automation matter.',
    'focus' => [
        [
            'kicker' => 'Cloud',
            'title' => 'Cloud Engineer',
            'icon' => 'cloud',
            'text' => 'Building and operating environments on AWS, Azure, and GCP — from networking and load balancing to scalable, cost-aware platforms.',
        ],
        [
            'kicker' => 'Delivery',
            'title' => 'DevOps',
            'icon' => 'repeat',
            'text' => 'Designing CI/CD with Jenkins, GitLab, and ArgoCD so teams can ship often, with quality gates from SonarQube and artifact flow through Nexus.',
        ],
        [
            'kicker' => 'Platform',
            'title' => 'Kubernetes',
            'icon' => 'layers',
            'text' => 'Running container platforms on AKS, EKS, and GKE with Docker, Helm, and cluster operations that stay observable and repeatable.',
        ],
        [
            'kicker' => 'Automation',
            'title' => 'Infrastructure as Code',
            'icon' => 'terminal',
            'text' => 'Terraform and Ansible for infrastructure, Bash and Python for glue work, and Prometheus plus Grafana so production is never a black box.',
        ],
    ],
    'skill_logos' => [
        ['name' => 'AWS', 'file' => 'skills/aws.svg'],
        ['name' => 'Azure', 'file' => 'skills/azure.svg'],
        ['name' => 'GCP', 'file' => 'skills/gcp.svg'],
        ['name' => 'Docker', 'file' => 'skills/docker.svg'],
        ['name' => 'Kubernetes', 'file' => 'skills/kubernetes.svg'],
        ['name' => 'Helm', 'file' => 'skills/helm.svg'],
        ['name' => 'Terraform', 'file' => 'skills/terraform.svg'],
        ['name' => 'Ansible', 'file' => 'skills/ansible.svg'],
        ['name' => 'Jenkins', 'file' => 'skills/jenkins.svg'],
        ['name' => 'GitLab', 'file' => 'skills/gitlab.svg'],
        ['name' => 'Argo CD', 'file' => 'skills/argocd.svg'],
        ['name' => 'Prometheus', 'file' => 'skills/prometheus.svg'],
        ['name' => 'Grafana', 'file' => 'skills/grafana.svg'],
        ['name' => 'Linux', 'file' => 'skills/linux.svg'],
        ['name' => 'Nginx', 'file' => 'skills/nginx.svg'],
        ['name' => 'GitHub', 'file' => 'skills/github.svg'],
        ['name' => 'Python', 'file' => 'skills/python.svg'],
        ['name' => 'Red Hat', 'file' => 'skills/redhat.svg'],
    ],
    'skills' => [
        'Cloud' => ['AWS', 'Azure', 'GCP'],
        'DevOps' => ['Jenkins', 'GitLab CI/CD', 'ArgoCD', 'Terraform', 'Ansible'],
        'Containers' => ['Docker', 'Kubernetes', 'AKS', 'EKS', 'GKE', 'Helm'],
        'Observability' => ['Prometheus', 'Grafana', 'GCP Monitoring'],
        'Systems' => ['Linux (RHEL)', 'Windows Server', 'Nginx', 'Apache'],
        'Tooling' => ['Git', 'GitHub', 'GitLab', 'Nexus', 'SonarQube', 'Bash', 'Python'],
        'Networking' => ['DNS', 'DHCP', 'VPN', 'Load Balancers'],
    ],
    'experience' => [
        [
            'role' => 'Senior DevOps Engineer',
            'company' => 'Jio Platforms Limited',
            'logo' => 'companies/jio.png',
            'location' => 'Bengaluru, India',
            'period' => 'Jan 2025 – Present',
            'current' => true,
            'points' => [
                'Designed and managed scalable CI/CD pipelines using Jenkins, GitLab, and ArgoCD.',
                'Automated deployments on Kubernetes (AKS, EKS, GKE) with Helm and Terraform.',
                'Implemented monitoring with Prometheus and Grafana.',
            ],
        ],
        [
            'role' => 'Senior DevOps Engineer',
            'company' => 'Karkinos Healthcare',
            'logo' => 'companies/karkinos.png',
            'logo_wide' => true,
            'location' => 'Bengaluru, India',
            'period' => 'Dec 2021 – Dec 2024',
            'current' => false,
            'points' => [
                'Deployed cloud solutions on AWS, Azure, and GCP, reducing deployment time by 40%.',
                'Managed Docker-based microservices and Kubernetes clusters.',
                'Maintained Terraform templates for infrastructure as code.',
                'Set up centralized logging, monitoring, and alerting for production.',
            ],
        ],
        [
            'role' => 'System Engineer',
            'company' => '3i Infotech Ltd.',
            'logo' => 'companies/3i.png',
            'location' => 'UAE',
            'period' => 'Dec 2020 – Nov 2021',
            'current' => false,
            'points' => [
                'Installed and maintained Linux infrastructure with ITIL-based operations.',
                'Improved reliability through monitoring and patch management.',
            ],
        ],
        [
            'role' => 'System Administrator',
            'company' => 'Farook Educational Society',
            'logo' => 'companies/farook.png',
            'location' => 'Kerala, India',
            'period' => 'May 2018 – Nov 2020',
            'current' => false,
            'points' => [
                'Configured routers, file servers, and network monitoring.',
                'Implemented backup and redundancy for data protection.',
            ],
        ],
        [
            'role' => 'Network Administrator',
            'company' => 'Xybo3 IT Solutions',
            'logo' => 'companies/xybo3.svg',
            'location' => 'Calicut, India',
            'period' => 'Jun 2016 – Apr 2018',
            'current' => false,
            'points' => [
                'Managed Active Directory, DNS, and DHCP.',
                'Supported and troubleshot Windows and Linux servers.',
            ],
        ],
    ],
    'education' => [
        'degree' => 'B.E. in Computer Science',
        'school' => 'University of Calicut, Kerala, India',
        'period' => '2012 – 2016',
        'logo' => 'companies/calicut.svg',
    ],
    'certifications' => [
        'Red Hat Certified System Administrator (RHCSA)',
        'Windows Server 2019 Administration (AD, DHCP, DNS)',
        'Ethical Hacking: System Hacking',
    ],
    'photos' => [
        'avatar' => 'assets/images/avatar.jpg',
        'about' => 'assets/images/about.jpg',
        'peek' => 'assets/images/peek.jpg',
        'portrait' => 'assets/images/portrait.jpg',
        'gallery_1' => 'assets/images/gallery-1.jpg',
        'gallery_2' => 'assets/images/gallery-2.jpg',
    ],
];
